//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace ThrustCurveBrowser.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2014/MetadataRequest")]
    [System.Xml.Serialization.XmlRootAttribute("metadata-request", Namespace="http://www.thrustcurve.org/2014/MetadataRequest", IsNullable=false)]
    public partial class metadatarequest {
        
        private string manufacturerField;
        
        private string impulseclassField;
        
        private decimal diameterField;
        
        private bool diameterFieldSpecified;
        
        private metadatarequestType typeField;
        
        private bool typeFieldSpecified;
        
        private string certorgField;
        
        private metadatarequestAvailability availabilityField;
        
        private bool availabilityFieldSpecified;
        
        /// <remarks/>
        public string manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("impulse-class")]
        public string impulseclass {
            get {
                return this.impulseclassField;
            }
            set {
                this.impulseclassField = value;
            }
        }
        
        /// <remarks/>
        public decimal diameter {
            get {
                return this.diameterField;
            }
            set {
                this.diameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool diameterSpecified {
            get {
                return this.diameterFieldSpecified;
            }
            set {
                this.diameterFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public metadatarequestType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cert-org")]
        public string certorg {
            get {
                return this.certorgField;
            }
            set {
                this.certorgField = value;
            }
        }
        
        /// <remarks/>
        public metadatarequestAvailability availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool availabilitySpecified {
            get {
                return this.availabilityFieldSpecified;
            }
            set {
                this.availabilityFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2014/MetadataRequest")]
    public enum metadatarequestType {
        
        /// <remarks/>
        SU,
        
        /// <remarks/>
        reload,
        
        /// <remarks/>
        hybrid,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.thrustcurve.org/2014/MetadataRequest")]
    public enum metadatarequestAvailability {
        
        /// <remarks/>
        regular,
        
        /// <remarks/>
        occasional,
        
        /// <remarks/>
        OOP,
        
        /// <remarks/>
        available,
        
        /// <remarks/>
        all,
    }
}
